Heart/Heart/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
]

Heart/core/urls.py
from django.urls import path
from . views import form_view, resault_view
urlpatterns = [
    path('',form_view, name="main_form"),
    path('result/',resault_view, name="resault_views")
]

Heart/core/models.py
from django.db import models

# Create your models here.

Heart/core/forms.py
from django import forms
select_sex = (("0","Female",), ("1","Male"))
select_cp = (("0","typical angina"),("1","atypical angina"),("2","non-anginal pain"),("3","asymptomatic"))
select_fbs = (("1","Yes"),("2","No"))
select_restecg = (("0","Normal"),("1","Having ST-T wave abnormality"),("2","Showing probable or definite left"))
select_exang = (("1","Yes"),("0","No"))
select_slope = (("1","Upsloping"),("2","Flat"),("3","Downsloping"))
select_ca=(("0","0"),("1","1"),("2","2"),("3","3"))
select_thal = (("0","Normal"),("1","Fixed defect"),("2","Blood flow normal"),("3","Reversible defect"))
class CreateFormForHeart(forms.Form):
    name=forms.CharField(max_length=100 )
    sex=forms.ChoiceField(choices=select_sex)
    cp=forms.ChoiceField(choices=select_cp)
    age=forms.IntegerField()
    trestbps=forms.IntegerField()
    chol=forms.IntegerField()
    fbs=forms.ChoiceField(choices=select_fbs)
    restecg=forms.ChoiceField(choices=select_restecg)
    thalach = forms.IntegerField()
    exang = forms.ChoiceField(choices=select_exang)
    oldpeak=forms.FloatField()
    slope=forms.ChoiceField(choices=select_slope)
    ca=forms.ChoiceField(choices=select_ca)
    thal=forms.ChoiceField(choices=select_thal)
# max_length trestbps

Heart/core/views.py
from django.shortcuts import render,HttpResponse,redirect
from .forms import CreateFormForHeart
import sklearn
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score,mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

heart=pd.read_csv('D:\Machine Learning\Project\heart.csv')
x=heart
y=heart.target
x.drop('target',axis=1,inplace=True)
sc = StandardScaler()
X = sc.fit_transform(x)
x_train,x_test,y_train,y_test=train_test_split(X,y,random_state=10,test_size=0.3,shuffle=True)

# this is for KNN
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)




# Create your views here.
def form_view(request):
    if request.method=="POST":
        print(request.POST)
        fm=CreateFormForHeart(request.POST)
        
        if fm.is_valid():
            user=fm.cleaned_data['name']
            age=fm.cleaned_data['age']
            sex=fm.cleaned_data['sex']
            cp=fm.cleaned_data['cp']
            trestbps=fm.cleaned_data['trestbps']
            chol=fm.cleaned_data['chol']
            fbs=fm.cleaned_data['fbs']
            restecg=fm.cleaned_data['restecg']
            thalach=fm.cleaned_data['thalach']
            exang=fm.cleaned_data['exang']
            oldpeak=fm.cleaned_data['oldpeak']
            slope=fm.cleaned_data['ca']
            thal=fm.cleaned_data['thal']
            ca=fm.cleaned_data['ca']
            
            X_DT=np.array([[age ,sex, cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,thal,ca]])
            X_DT=sc.transform(X_DT)
            X_DT_prediction=dt.predict(X_DT)
            result=X_DT_prediction[0]
           
            

    else:
        fm=CreateFormForHeart()
    return render(request ,'Mainapp/index.html',{'form':fm})


def resault_view(request):
    print(my_result)
    return render(request ,'Mainapp/resault.html')

Heart/core/templates/Base/Base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    
    <title>Django Heart</title>
   
  </head>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,500;1,400&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@700&display=swap" rel="stylesheet">
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand text" href="#">Heart_Webapp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse container-fluid" id="navbarNavAltMarkup">
        
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>

Heart/core/templates/Mainapp/index.html
{% extends 'Base/Base.html' %}

{% block content %}
<div class="main_form container my-5">
  <form action="" method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_name" class="form-label">User name:</label>
      {{form.name}}
    </div>

    
    <div class="mb-3">
      <label for="id_age" class="form-label">Age:</label>
      {{form.age}}
    </div>


    <div class="mb-3">
      <label for="id_sex" class="form-label">Gender :</label>
     {{form.sex}}
    </div>

    <div class="mb-3">
      <label for="id_cp">Chest pain :</label>
      {{form.cp}}
    </div>

    <div class="mb-3">
      <label for="id_trestbps" class="form-label">Trestbps:</label>
      {{form.trestbps}}
    </div>


    <div class="mb-3">
      <label for="id_chol" class="form-label">Cholestoral:</label>
      {{form.chol}}
    </div>

    <div class="mb-3">
      <label for="id_fbs">Fasting Blood Sugar: <p>fasting blood sugar >120 </p></label>
      {{form.fbs}}
    </div>

    <div class="mb-3">
      <label for="id_restecg">Electrocardiographic results :</label>
      {{form.restecg}}
    </div>

    <div class="mb-3">
      <label for="id_thalach" class="form-label">Maximum heart rate (thalach) :</label>
      {{form.thalach}}
    </div>
 

    <div class="mb-3">
      <label for="id_exang">Exercise induced angina:</label>
      {{form.exang}}
    </div>
 
    <div class="mb-3">
      <label for="id_oldpeak" class="form-label">Oldpeak:</label>
      {{form.oldpeak}}
    </div>

    <div class="mb-3">
      <label for="id_slope">Slope :</label>
      {{form.slope}}
    </div>
 

    <div class="mb-3">
      <label for="id_ca">Ca :</label>
      {{form.ca}}
    </div>



    <div class="mb-3">
      <label for="id_thal">Thal :</label>
      {{form.thal}}
    </div>

    <button type="submit" class="btn btn-info">Submit All</button>
  </form>
</div>
{% endblock %}